TEXT_GAMEOVER  = "YOU COMPLETED ";
TEXT_SUDOKU    = " WORDOKU";
TEXT_IN        = " IN ";
TEXT_HELP_USED = "YOU USED THE FOLLOWING HELP:";
TEXT_HELPS_USED= "YOU USED THE FOLLOWING HELPS:";
TEXT_HELP_NOTE = "NOTES AUTOFILL";
TEXT_HELP_SOLVE= "SOLVER";
TEXT_HELP_TIME = "SET NO TIME";
TEXT_HELP_HINT = " HINT";
TEXT_HELP_HINTS = " HINTS";
TEXT_SCORE     = "SCORE:";
TEXT_PLAY      = "PLAY";
TEXT_RESTART   = "RESTART";
TEXT_TIME      = "TIME";
TEXT_GENERATE_SUDOKU = "GENERATING WORDOKU. PLEASE WAIT";
TEXT_PAUSE     = "PAUSE";

TEXT_DEVELOPED = "developed by";

TEXT_INFO_SOLVE = "(all points lost)";
TEXT_INFO_NOTE = "(half of all points lost)";
TEXT_INFO_HINT = "points per hint)";

TEXT_TOP_MODE  = "SELECT YOUR LEVEL";
TEXT_EASY      = "BEGINNER";
TEXT_MEDIUM    = "INTERMEDIATE";
TEXT_HARD      = "ADVANCED";

TEXT_HELP0     = "RULES";
TEXT_HELP1     = "FILL IN THE BLANKS WITH THE LETTERS BELOW. EACH ROW, COLUMN OR 3X3 BLOCK, MUST CONTAIN A LETTER EXACTLY ONCE";

TEXT_HELP0_PAGE2 = "HOW-TO";
TEXT_HELP1_PAGE2 = "USE KEYBOARD OR LETTER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";
TEXT_HELP1_MOB_PAGE2 = "USE LETTER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";

TEXT_HELP2_PAGE2 = '"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE LETTER YOU WANT TO ENTER';
TEXT_HELP3_PAGE2 = '"LETTER FIRST" MODE: SELECT THE LETTER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';
TEXT_HELP4_PAGE2 = 'MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK';

TEXT_FILL_WITH_NOTE = "FILL THE BOARD WITH NOTES";
TEXT_DELETE_ALL_NOTE = "DELETE ALL NOTES";
TEXT_SOLVE = "SOLVE THE WORDOKU";
TEXT_RESET = "RESET THE WORDOKU";
TEXT_SETNOTIME = "PLAY WITHOUT TIME";
TEXT_GETHINT = "GET A HINT";
TEXT_FULLSCREEN = "FULL SCREEN";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";